- name: Demo on play level variable
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}  




- name: Load vars from a file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}  




- name: variable from role
  hosts: all
  vars: 
    URL_Play: paly.example.com
  roles:
    - sample        



- name: Demo on register variables
  hosts: all
  tasks:
    - name: Run uptime shell command
      ansible.builtin.shell: uptime    
      register: output
    - name: print output
      ansible.builtin.debug:
        msg: '{{ output }}'
      
